# Generated by Django 4.0.3 on 2022-05-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Pre_Image',
        ),
    ]
