# Generated by Django 3.2 on 2022-05-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_auto_20220518_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedimage',
            name='img',
            field=models.ImageField(upload_to='predicted_image'),
        ),
    ]
