# Generated by Django 3.2 on 2022-05-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0006_alter_predictedimage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedimage',
            name='img',
            field=models.ImageField(upload_to='predicted_images'),
        ),
    ]
